DATA_PATH = '../data'
INITIAL_DATASET_PATH = f'{DATA_PATH}/INITIAL_DATASET.csv'
INITIAL_DATASET_PATH_TEST = f'{DATA_PATH}/INITIAL_DATASET_test.csv'
REPOS_PATH = '../repos'
MAC_TOOL_PATH = 'macTool.jar'
MAC_TOOL_OUTPUT = f'{DATA_PATH}/macTool_output'
MAC_TOOL_FILES = f'{DATA_PATH}/macTool_output.zip'
LABELLED_DATASET_PATH = f'{DATA_PATH}/LABELLED_DATASET.csv'
DATASET_DOWNLOAD_LINK = {"https://drive.google.com/uc?export=download&confirm=iIXP&id=1OwMq81W2xajsHuG6HKBzZoL0Fp3_HL5d"}
